2020-04-21 00:18:05,707 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 237757ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 00:33:37,130 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 931418ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 00:49:28,218 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 931084ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 01:05:20,074 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 931851ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 01:21:30,863 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 930611ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 01:32:16,889 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 626012ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 02:02:31,008 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 1814109ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 02:33:05,060 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 1813708ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 03:14:27,097 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 2461682ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 03:31:19,620 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 1012265ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 03:33:00,360 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 99963ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 03:39:52,371 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 411720ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 04:20:27,445 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 2414297ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 04:51:06,462 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 1818086ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 05:01:57,405 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 630002ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 05:32:56,296 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 1817892ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 05:53:41,088 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 1224307ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 06:28:19,442 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 2057849ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 07:10:49,902 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 2530292ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 07:31:32,944 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 1222239ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 07:42:20,765 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 627143ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 08:32:46,748 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 3005178ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 08:42:53,373 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 585470ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 09:13:29,409 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 86382ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 09:40:47,722 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 1617915ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 09:44:20,400 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 172143ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 12:32:43,664 ERROR 7613 nodejs.ClusterClientNoResponseError: client no response in 1439625ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 7613
hostname: bidaodeMacBook-Pro.local

2020-04-21 17:41:45,926 ERROR 10415 nodejs.ClusterClientNoResponseError: client no response in 216022ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/bidao/project/myself/rc-backend/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 10415
hostname: bogon

2020-04-21 18:45:09,120 ERROR 12853 [-/127.0.0.1/-/13ms GET /public/22.txt] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/public/22.txt'
ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/public/22.txt'
errno: -2
code: "ENOENT"
syscall: "open"
path: "/Users/bidao/project/myself/rc-backend/app/public/22.txt"
name: "ENOENTError"
pid: 12853
hostname: bogon

2020-04-21 18:45:09,523 ERROR 12853 [-/127.0.0.1/-/1ms GET /public/22.txt] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/public/22.txt'
ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/public/22.txt'
errno: -2
code: "ENOENT"
syscall: "open"
path: "/Users/bidao/project/myself/rc-backend/app/public/22.txt"
name: "ENOENTError"
pid: 12853
hostname: bogon

2020-04-21 18:52:30,353 ERROR 12930 [-/127.0.0.1/-/12ms GET /static/23333546456.txt] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
errno: -2
code: "ENOENT"
syscall: "open"
path: "/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt"
name: "ENOENTError"
pid: 12930
hostname: bogon

2020-04-21 18:52:30,877 ERROR 12930 [-/127.0.0.1/-/1ms GET /static/23333546456.txt] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
errno: -2
code: "ENOENT"
syscall: "open"
path: "/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt"
name: "ENOENTError"
pid: 12930
hostname: bogon

2020-04-21 18:52:32,491 ERROR 12930 [-/127.0.0.1/-/3ms GET /static/23333546456.txt] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
errno: -2
code: "ENOENT"
syscall: "open"
path: "/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt"
name: "ENOENTError"
pid: 12930
hostname: bogon

2020-04-21 18:52:33,359 ERROR 12930 [-/127.0.0.1/-/1ms GET /static/23333546456.txt] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
errno: -2
code: "ENOENT"
syscall: "open"
path: "/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt"
name: "ENOENTError"
pid: 12930
hostname: bogon

2020-04-21 18:52:34,204 ERROR 12930 [-/127.0.0.1/-/1ms GET /static/23333546456.txt] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
errno: -2
code: "ENOENT"
syscall: "open"
path: "/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt"
name: "ENOENTError"
pid: 12930
hostname: bogon

2020-04-21 18:52:35,174 ERROR 12930 [-/127.0.0.1/-/1ms GET /static/23333546456.txt] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
errno: -2
code: "ENOENT"
syscall: "open"
path: "/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt"
name: "ENOENTError"
pid: 12930
hostname: bogon

2020-04-21 18:52:36,191 ERROR 12930 [-/127.0.0.1/-/1ms GET /static/23333546456.txt] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
errno: -2
code: "ENOENT"
syscall: "open"
path: "/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt"
name: "ENOENTError"
pid: 12930
hostname: bogon

2020-04-21 18:52:41,389 ERROR 12930 [-/127.0.0.1/-/1ms GET /static/23333546456.txt] nodejs.ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
ENOENTError: ENOENT: no such file or directory, open '/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt'
errno: -2
code: "ENOENT"
syscall: "open"
path: "/Users/bidao/project/myself/rc-backend/app/static/23333546456.txt"
name: "ENOENTError"
pid: 12930
hostname: bogon

2020-04-21 19:27:26,967 ERROR 12930 [-/127.0.0.1/-/62ms POST /api/v1/files] nodejs.SequelizeValidationError: string violation: name cannot be an array or an object
    at Promise.all.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:74:15)
From previous event:
    at InstanceValidator._validate (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:72:8)
    at runHooks.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:107:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at InstanceValidator._validateAndRunHooks (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:106:8)
    at InstanceValidator.validate (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:90:38)
    at model.validate (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:4138:49)
    at Promise.try (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3903:21)
    at model.save (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3900:23)
    at Function.create (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:2228:8)
    at HomeController.store (/Users/bidao/project/myself/rc-backend/app/controller/home.js:31:39)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at next (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:45:18)
    at /Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/bidao/project/myself/rc-backend/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
From previous event:
    at model.save (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3900:23)
    at Function.create (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:2228:8)
    at HomeController.store (/Users/bidao/project/myself/rc-backend/app/controller/home.js:31:39)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at next (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:45:18)
    at /Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/bidao/project/myself/rc-backend/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at nosniff (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/nosniff.js:8:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at noopen (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/noopen.js:8:11)
name: "SequelizeValidationError"
errors: [{"message":"name cannot be an array or an object","type":"string violation","path":"name","value":{"name":"","content":""},"origin":"CORE","instance":{"id":null,"name":{"name":"","content":""},"url":"/static/[object Object].txt"},"validatorKey":"not_a_string","validatorName":null,"validatorArgs":[]}]
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8090","vary":"Origin"}
pid: 12930
hostname: bogon

2020-04-21 19:28:03,256 ERROR 13033 [-/127.0.0.1/-/39ms POST /api/v1/files] nodejs.SequelizeValidationError: string violation: name cannot be an array or an object
    at Promise.all.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:74:15)
From previous event:
    at InstanceValidator._validate (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:72:8)
    at runHooks.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:107:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at InstanceValidator._validateAndRunHooks (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:106:8)
    at InstanceValidator.validate (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:90:38)
    at model.validate (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:4138:49)
    at Promise.try (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3903:21)
    at model.save (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3900:23)
    at Function.create (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:2228:8)
    at HomeController.store (/Users/bidao/project/myself/rc-backend/app/controller/home.js:31:39)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at next (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:45:18)
    at /Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/bidao/project/myself/rc-backend/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
From previous event:
    at model.save (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3900:23)
    at Function.create (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:2228:8)
    at HomeController.store (/Users/bidao/project/myself/rc-backend/app/controller/home.js:31:39)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at next (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:45:18)
    at /Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/bidao/project/myself/rc-backend/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at nosniff (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/nosniff.js:8:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at noopen (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/noopen.js:8:11)
name: "SequelizeValidationError"
errors: [{"message":"name cannot be an array or an object","type":"string violation","path":"name","value":{"name":"nihao","content":"2333"},"origin":"CORE","instance":{"id":null,"name":{"name":"nihao","content":"2333"},"url":"/static/[object Object].txt"},"validatorKey":"not_a_string","validatorName":null,"validatorArgs":[]}]
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8090","vary":"Origin"}
pid: 13033
hostname: bogon

2020-04-21 19:29:36,694 ERROR 13046 [-/127.0.0.1/-/26ms POST /api/v1/files] nodejs.SequelizeValidationError: string violation: name cannot be an array or an object
    at Promise.all.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:74:15)
From previous event:
    at InstanceValidator._validate (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:72:8)
    at runHooks.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:107:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at InstanceValidator._validateAndRunHooks (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:106:8)
    at InstanceValidator.validate (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/instance-validator.js:90:38)
    at model.validate (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:4138:49)
    at Promise.try (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3903:21)
    at model.save (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3900:23)
    at Function.create (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:2228:8)
    at HomeController.store (/Users/bidao/project/myself/rc-backend/app/controller/home.js:31:39)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at next (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:45:18)
    at /Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/bidao/project/myself/rc-backend/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
From previous event:
    at model.save (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3900:23)
    at Function.create (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:2228:8)
    at HomeController.store (/Users/bidao/project/myself/rc-backend/app/controller/home.js:31:39)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at next (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:45:18)
    at /Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/bidao/project/myself/rc-backend/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at nosniff (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/nosniff.js:8:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at noopen (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/noopen.js:8:11)
name: "SequelizeValidationError"
errors: [{"message":"name cannot be an array or an object","type":"string violation","path":"name","value":{"name":"nihao","content":"2333"},"origin":"CORE","instance":{"id":null,"name":{"name":"nihao","content":"2333"},"url":"/static/[object Object].txt"},"validatorKey":"not_a_string","validatorName":null,"validatorArgs":[]}]
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8090","vary":"Origin"}
pid: 13046
hostname: bogon

2020-04-21 19:31:17,602 ERROR 13050 [-/undefined/-/73ms POST /api/v1/files] nodejs.SequelizeDatabaseError: Incorrect integer value: 'new' for column 'name' at row 1
    at Query.formatError (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Execute.handler [as onResult] (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Execute.execute (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Query.run (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:39:12)
    at runHooks.then.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:645:29)
From previous event:
    at Promise.try.then.connection (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:645:12)
From previous event:
    at Promise.resolve.retry (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:641:10)
    at /Users/bidao/project/myself/rc-backend/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/Users/bidao/project/myself/rc-backend/node_modules/retry-as-promised/index.js:60:10)
    at Promise.try (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:631:30)
From previous event:
    at Sequelize.query (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:580:23)
    at QueryInterface.insert (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/query-interface.js:885:27)
    at Promise.try.then.then.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3987:52)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at model.save (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3964:8)
    at Function.create (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:2228:8)
    at HomeController.store (/Users/bidao/project/myself/rc-backend/app/controller/home.js:31:39)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at next (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:45:18)
    at /Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/bidao/project/myself/rc-backend/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at nosniff (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/nosniff.js:8:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: 'new' for column 'name' at row 1","sql":"INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);","parameters":["new","/static/new.txt"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: 'new' for column 'name' at row 1","sql":"INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);","parameters":["new","/static/new.txt"]}
sql: "INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);"
parameters: ["new","/static/new.txt"]
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8090","vary":"Origin"}
headerSent: true
pid: 13050
hostname: bogon

2020-04-21 19:34:11,973 ERROR 13061 [-/undefined/-/94ms POST /api/v1/files] nodejs.SequelizeDatabaseError: Incorrect integer value: 'cc' for column 'name' at row 1
    at Query.formatError (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Execute.handler [as onResult] (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Execute.execute (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Query.run (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:39:12)
    at runHooks.then.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:645:29)
From previous event:
    at Promise.try.then.connection (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:645:12)
From previous event:
    at Promise.resolve.retry (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:641:10)
    at /Users/bidao/project/myself/rc-backend/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/Users/bidao/project/myself/rc-backend/node_modules/retry-as-promised/index.js:60:10)
    at Promise.try (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:631:30)
From previous event:
    at Sequelize.query (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:580:23)
    at QueryInterface.insert (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/query-interface.js:885:27)
    at Promise.try.then.then.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3987:52)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at model.save (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3964:8)
    at Function.create (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:2228:8)
    at HomeController.store (/Users/bidao/project/myself/rc-backend/app/controller/home.js:32:39)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at next (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:45:18)
    at /Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/bidao/project/myself/rc-backend/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at nosniff (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/nosniff.js:8:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: 'cc' for column 'name' at row 1","sql":"INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);","parameters":["cc","/static/cc.txt"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: 'cc' for column 'name' at row 1","sql":"INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);","parameters":["cc","/static/cc.txt"]}
sql: "INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);"
parameters: ["cc","/static/cc.txt"]
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8090","vary":"Origin"}
headerSent: true
pid: 13061
hostname: bogon

2020-04-21 22:11:30,378 ERROR 13269 [-/undefined/-/153ms POST /api/v1/files] nodejs.SequelizeDatabaseError: Incorrect integer value: '' for column 'name' at row 1
    at Query.formatError (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Execute.handler [as onResult] (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Execute.execute (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Query.run (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:39:12)
    at runHooks.then.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:645:29)
From previous event:
    at Promise.try.then.connection (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:645:12)
From previous event:
    at Promise.resolve.retry (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:641:10)
    at /Users/bidao/project/myself/rc-backend/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/Users/bidao/project/myself/rc-backend/node_modules/retry-as-promised/index.js:60:10)
    at Promise.try (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:631:30)
From previous event:
    at Sequelize.query (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:580:23)
    at QueryInterface.insert (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/query-interface.js:885:27)
    at Promise.try.then.then.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3987:52)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at model.save (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3964:8)
    at Function.create (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:2228:8)
    at HomeController.store (/Users/bidao/project/myself/rc-backend/app/controller/home.js:32:39)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at next (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:45:18)
    at /Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/bidao/project/myself/rc-backend/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at nosniff (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/nosniff.js:8:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: '' for column 'name' at row 1","sql":"INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);","parameters":["","/static/.txt"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: '' for column 'name' at row 1","sql":"INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);","parameters":["","/static/.txt"]}
sql: "INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);"
parameters: ["","/static/.txt"]
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8090","vary":"Origin"}
headerSent: true
pid: 13269
hostname: bidaodeMacBook-Pro.local

2020-04-21 22:12:51,138 ERROR 13282 [-/undefined/-/182ms POST /api/v1/files] nodejs.SequelizeDatabaseError: Incorrect integer value: 'hello' for column 'name' at row 1
    at Query.formatError (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Execute.handler [as onResult] (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Execute.execute (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Query.run (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:39:12)
    at runHooks.then.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:645:29)
From previous event:
    at Promise.try.then.connection (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:645:12)
From previous event:
    at Promise.resolve.retry (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:641:10)
    at /Users/bidao/project/myself/rc-backend/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/Users/bidao/project/myself/rc-backend/node_modules/retry-as-promised/index.js:60:10)
    at Promise.try (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:631:30)
From previous event:
    at Sequelize.query (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:580:23)
    at QueryInterface.insert (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/query-interface.js:885:27)
    at Promise.try.then.then.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3987:52)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at model.save (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3964:8)
    at Function.create (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:2228:8)
    at HomeController.store (/Users/bidao/project/myself/rc-backend/app/controller/home.js:32:39)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at next (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:45:18)
    at /Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/bidao/project/myself/rc-backend/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at nosniff (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/nosniff.js:8:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: 'hello' for column 'name' at row 1","sql":"INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);","parameters":["hello","/static/hello.txt"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: 'hello' for column 'name' at row 1","sql":"INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);","parameters":["hello","/static/hello.txt"]}
sql: "INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);"
parameters: ["hello","/static/hello.txt"]
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8090","vary":"Origin"}
headerSent: true
pid: 13282
hostname: bidaodeMacBook-Pro.local

2020-04-21 22:14:27,861 ERROR 13285 [-/undefined/-/106ms POST /api/v1/files] nodejs.SequelizeDatabaseError: Incorrect integer value: 'arena' for column 'name' at row 1
    at Query.formatError (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Execute.handler [as onResult] (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Execute.execute (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/bidao/project/myself/rc-backend/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Query.run (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/dialects/mysql/query.js:39:12)
    at runHooks.then.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:645:29)
From previous event:
    at Promise.try.then.connection (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:645:12)
From previous event:
    at Promise.resolve.retry (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:641:10)
    at /Users/bidao/project/myself/rc-backend/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/Users/bidao/project/myself/rc-backend/node_modules/retry-as-promised/index.js:60:10)
    at Promise.try (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:631:30)
From previous event:
    at Sequelize.query (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/sequelize.js:580:23)
    at QueryInterface.insert (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/query-interface.js:885:27)
    at Promise.try.then.then.then (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3987:52)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at model.save (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:3964:8)
    at Function.create (/Users/bidao/project/myself/rc-backend/node_modules/sequelize/lib/model.js:2228:8)
    at HomeController.store (/Users/bidao/project/myself/rc-backend/app/controller/home.js:32:39)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/bidao/project/myself/rc-backend/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at next (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:45:18)
    at /Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:44:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at /Users/bidao/project/myself/rc-backend/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/bidao/project/myself/rc-backend/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
    at nosniff (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/lib/middlewares/nosniff.js:8:11)
    at dispatch (/Users/bidao/project/myself/rc-backend/node_modules/egg-security/node_modules/koa-compose/index.js:42:32)
name: "SequelizeDatabaseError"
parent: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: 'arena' for column 'name' at row 1","sql":"INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);","parameters":["arena","/static/arena.txt"]}
original: {"code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD","errno":1366,"sqlState":"HY000","sqlMessage":"Incorrect integer value: 'arena' for column 'name' at row 1","sql":"INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);","parameters":["arena","/static/arena.txt"]}
sql: "INSERT INTO `file` (`id`,`name`,`url`) VALUES (DEFAULT,?,?);"
parameters: ["arena","/static/arena.txt"]
headers: {"Access-Control-Allow-Origin":"http://127.0.0.1:8090","vary":"Origin"}
headerSent: true
pid: 13285
hostname: bidaodeMacBook-Pro.local

